# Generated by Django 3.1.7 on 2021-10-08 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='商品简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=ckeditor.fields.RichTextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=ckeditor.fields.RichTextField(default='', help_text='类别描述', verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='desc',
            field=ckeditor.fields.RichTextField(default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述'),
        ),
    ]
